<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercise 4 : Analyze #6</title>
</head>

<body>
    <h1>Exercise 4 : Analyze #6</h1>
    <script>
        let resolveAfter2Seconds = function () {
            console.log("starting slow promise");
            return new Promise(resolve => {
                setTimeout(function () {
                    resolve("slow");
                    console.log("slow promise is done");
                }, 2000);
            });
        };

        let resolveAfter1Second = function () {
            console.log("starting fast promise");
            return new Promise(resolve => {
                setTimeout(function () {
                    resolve("fast");
                    console.log("fast promise is done");
                }, 1000);
            });
        };

        // This function does not handle errors. See warning below!
        let parallelPromise = function () {
            console.log('==PARALLEL with Promise.then==');
            resolveAfter2Seconds().then((message) => console.log(message));
            resolveAfter1Second().then((message) => console.log(message));
        }

        setTimeout(parallelPromise, 13000)

        // after 13 s
        // ==PARALLEL with Promise.then==
        // starting slow promise
        // starting fast promise

        // fast promise is done
        // fast
        
        // slow promise is done
        // slow

    </script>

</body>

</html>